name: Tests

on: [push, pull_request]

jobs:
  tests-linux-amd64:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Run tests linux-amd64
      run: |
        scripts/tests-ubuntu-amd64.sh

  tests-macos-amd64:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests macos-amd64
      run: |
        scripts/tests-macos-amd64.sh

  tests-windows-amd64:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: Run tests windows-amd64
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T release --tests --prefix=out/
        ./waf.bat install
        cd out
        $env:Path = "bin";
        ./unittest.exe
